[package]
name = "hnf"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
reqwest = { version = "0.12.20", features = ["blocking", "json"] }
serde = { version =  "1.0.219", features = ["derive"] }
