name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/hnf${{ runner.os == 'Windows' && '.exe' || '' }}
