name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release

      - name: Rename binary
        run: |
          BIN_NAME="hnf"
          case "${{ matrix.os }}" in
            ubuntu-latest)   OUT="${BIN_NAME}-x86_64-unknown-linux-gnu" ;;
            macos-latest)    OUT="${BIN_NAME}-x86_64-apple-darwin" ;;
            windows-latest)  OUT="${BIN_NAME}-x86_64-pc-windows-msvc.exe" ;;
          esac

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv target/release/${BIN_NAME}.exe "$OUT"
          else
            mv target/release/${BIN_NAME} "$OUT"
          fi

          echo "OUT=$OUT" >> $GITHUB_ENV

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.OUT }}
